services:
  - type: web
    name: wedding-website
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: COUPLE_EMAIL
        value: wong.jennicaarah@gmail.com
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
